// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StorageInterface is an autogenerated mock type for the StorageInterface type
type StorageInterface struct {
	mock.Mock
}

// GetOriginalLink provides a mock function with given fields: originalLink
func (_m *StorageInterface) GetOriginalLink(originalLink string) (string, error) {
	ret := _m.Called(originalLink)

	if len(ret) == 0 {
		panic("no return value specified for GetOriginalLink")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(originalLink)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(originalLink)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(originalLink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetShortLink provides a mock function with given fields: shortLink
func (_m *StorageInterface) GetShortLink(shortLink string) (string, error) {
	ret := _m.Called(shortLink)

	if len(ret) == 0 {
		panic("no return value specified for GetShortLink")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(shortLink)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(shortLink)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(shortLink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveLinks provides a mock function with given fields: shortLink, originalLink
func (_m *StorageInterface) SaveLinks(shortLink string, originalLink string) {
	_m.Called(shortLink, originalLink)
}

// NewStorageInterface creates a new instance of StorageInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageInterface {
	mock := &StorageInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
